const passwordSlot = document.getElementById("passwordSlot"); //we need to insert values in this element which will be generated by createPassword() function

const copyButton = document.getElementById("copyButton"); //we would want to copy the latest value from the above element and paste it in the clipboard

const rangeLabel = document.getElementById("rangeLabel"); // we would want to get the value from the range element and insert it in this element.

const range = document.getElementById("range"); // Obviously we would want this to get the length value

const numberCheckbox = document.getElementById("numberCheckbox"); // we want this to see if it is checked or not and based on that we need to modify the results with createPassword() function

const charCheckbox = document.getElementById("charCheckbox"); // same as above ...



//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
let rangeValue = range.value;

rangeLabel.innerHTML = `Length :${rangeValue}`

//call the createPassword() on changing the range values
range.addEventListener("input",(e)=>{
    rangeValue = e.target.value //latest value injected into rangeValue 
    rangeLabel.innerHTML = `Length :${e.target.value}`
    createPassword()
})

//call the createPassword() on changing of numberCheckbox
numberCheckbox.addEventListener('change',(e)=>{
    createPassword()
});

//call the createPassword() on changing of charCheckbox
charCheckbox.addEventListener('change',(e)=>{
    createPassword()
});

//calling the copyToClipboard 
copyButton.addEventListener('click',()=>{
    copyToClipboard()
})



function createPassword(){
    
    let pass = "";
    let str = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

    if (numberCheckbox.checked) {
        str += "1234567890" 
    }

    if (charCheckbox.checked) {
        str += "!@#$%^&*()-_=+\|[]{};:/?."
    }

    for (let i = 0; i < rangeValue; i++) {
      let char = Math.floor(Math.random() * str.length + 1)
      pass += str.charAt(char)
    }
    
    passwordSlot.setAttribute('value',pass);
    return pass;
}


function copyToClipboard(){
    let copyValue = passwordSlot;
    copyValue.select();
    copyValue.setSelectionRange(0, 99999);
    window.navigator.clipboard.writeText(copyValue.value);
};
