const passwordSlot = document.getElementById("passwordSlot"); //we need to insert values in this element which will be generated by createPassword() function

const copyButton = document.getElementById("copyButton"); //we would want to copy the latest value from the above element and paste it in the clipboard

const rangeLabel = document.getElementById("rangeLabel"); // we would want to get the value from the range element and insert it in this element.

const range = document.getElementById("range"); // Obviously we would want this to get the length value

const numberCheckbox = document.getElementById("numberCheckbox"); // we want this to see if it is checked or not and based on that we need to modify the results with createPassword() function

const charCheckbox = document.getElementById("charCheckbox"); // same as above ...


function createPassword(){
    //the logic goes here
}